PORT = 7932
VIEW_DISTANCE = 8
VIEW_DISTANCE_BOX = 2 * VIEW_DISTANCE + 1
MAX_LOADED_CHUNKS = VIEW_DISTANCE_BOX ** 2
REACH_DISTANCE = 4
REACH_DISTANCE_SQ = REACH_DISTANCE * REACH_DISTANCE
MOVE_SPEED = 3
GRAVITY = -9.8
